development:
  adapter: postgresql
  database: hxl_dev
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  user : jkachiro
  password : 123456

test:
  adapter: postgresql
  database: hxl_test
  pool: 5
  host: localhost
  timeout: 5000
  user: jkachiro
  password: 123456


production:
  adapter: postgresql
  encoding: unicode
  host: ec2-23-21-64-61.compute-1.amazonaws.com
  database: cctnohkslf
  pool: 5
  username: cctnohkslf
  password: 6KwXIAeXWUOo3TE6VzkP
